name: Run

on:
  workflow_dispatch:
  repository_dispatch:

  # UTC时间，对应Beijing时间 9：01
  schedule:
      - cron: "01 1 * * *"

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      uses: coactions/setup-xvfb@main
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}